export const ClearedList = [
    {
        student_id: "MA21010401",
        name: "Steven Acosta",
        course: "BSIS",
        year: "First Year",
        section: "B",
        receipt: "ajkdhajks827689q2.png",
    },
    {
        student_id: "MA21010402",
        name: "Maria Lopez",
        course: "BSIS",
        year: "Second Year",
        section: "A",
        receipt: "askdakdjq3askld23.png",
    },
    {
        student_id: "MA21010403",
        name: "John Doe",
        course: "BSOM",
        year: "First Year",
        section: "C",
        receipt: "khasdjks23423ksakljd.png",
    },
    {
        student_id: "MA21010404",
        name: "Jane Smith",
        course: "BSAIS",
        year: "Third Year",
        section: "A",
        receipt: "asjkdhaq3424asdj.png",
    },
    {
        student_id: "MA21010405",
        name: "Mark Davis",
        course: "BSIS",
        year: "Second Year",
        section: "B",
        receipt: "aklsdjak23423dasad.png",
    },
    {
        student_id: "MA21010406",
        name: "Sophia Lee",
        course: "BTVTED",
        year: "Fourth Year",
        section: "A",
        receipt: "kasjdkla34dfsk23.png",
    },
];